[package]
name = "botchang"
version = "0.1.0"
authors = ["sasami-san"]
edition = "2018"

[dependencies]
twitchchat = "0.7"
regex = "1.3"
lazy_static = "1.4"
dotenv = "0.15"
obs-websocket = { path = "../obs-websocket-rs" }
